### ISSUE TITLE
Unable to minify...

### ISSUE THREAD

**Issue by gleba** [marko-js-samples/ui-components-playground-lasso-express#6]
When compile with `isProduction:true`
we have this errors:
` Unable to minify the following code for [commonjs-def: path="/warp10$1.3.3/src/stringifyPrepar/...`
` Unable to minify the following code for [commonjs-def: path="/warp10$1.3.3/src/serialize/...`

its only on windows, on unux systems everything is okay

Thanks.

**Comment by StarpTech** [comment]
Hi @gleba I would post this on https://github.com/marko-js/marko here it will go under

**Comment by patrick-steele-idem** [comment]
@gleba are you still seeing this issue?

Those dependencies that are failing to be minified should not be included in the browser bundles. It looks like maybe the remapping for browser dependencies is not working on a Windows machine based on what you have said. I don't have a Window VM to test with at the moment and it would be great if I could get your help debugging. 

If you run the tests for `lasso-resolve-from` on your Windows machine do they pass?:

```
git clone https://github.com/lasso-js/lasso-resolve-from
cd lasso-resolve-from
npm install
npm test
```

Thanks for reporting the problem and helping to debug.

**Comment by gleba** [comment]
@patrick-steele-idem yes, 
after update to "Upgraded to marko@4.0.0-rc.19" errors still present.
in 'lasso-resolve-from' too many errors
http://x.gleb.pw/2017-02-23_18.04.51.png

**Comment by basickarl** [comment]
I am receiving the same on Linux:

```
Unable to minify the following code for [commonjs-def: path="/mkr$2.0.0/src/client/components/app-sign-in/index.marko"] at line 7 column 14:
------------------------------------
$_mod.def("/mkr$2.0.0/src/client/components/app-sign-in/index.marko", function(require, exports, module, __filename, __dirname) { // Compiled using marko@4.1.3 - DO NOT EDIT
"use strict";

var marko_template = module.exports = require('/marko$4.1.3/vdom'/*"marko/vdom"*/).t(),
    marko_component = {
        onMount: function() {
          let something;
        }
      },
    marko_components = require('/marko$4.1.3/components/index-browser'/*"marko/components"*/),
    marko_registerComponent = marko_components.rc,
    marko_componentType = marko_registerComponent("/mkr$2.0.0/src/client/components/app-sign-in/index.marko", function() {
      return module.exports;
    });

function render(input, out, __component, component, state) {
  var data = input;

  out.e("SECTION", {
      id: __component.id
    }, 0, 4);
}

marko_template._ = marko_components.r(render, {
    type: marko_componentType
  }, marko_component);

marko_template.Component = marko_components.c(marko_component, marko_template._);

});
------------------------------------
```

I know why it happens though. My `index.marko` below:

```
class {
  onMount() {
      let something; // <--- let
  }
}

<section>
</section>
```

It's the `let` keyword.
